# Generated by Django 4.2.3 on 2023-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('modified_data', models.DateTimeField(auto_now=True)),
                ('prize', models.TextField()),
            ],
        ),
    ]
