# Generated by Django 4.2.3 on 2023-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
