# Generated by Django 4.2.3 on 2023-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_product_description_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.FloatField(max_length=1000000),
        ),
    ]
