# Generated by Django 4.2.3 on 2023-07-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_product_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
